// Generated by scripts/refresh-listings.mjs after a successful source check.
export const refreshState = {
  "dataUpdatedAt": "2026-08-03T04:03:53.746Z",
  "lastRefreshAttemptAt": "2026-08-03T04:03:53.746Z",
  "verifiedSourceCount": 2,
  "totalSourceCount": 12,
  "sourceStatuses": {
    "https://www.equityapartments.com/san-francisco/rincon-hill/340-fremont-apartments": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "lastSuccessfulAt": "2026-08-03T04:03:53.746Z",
      "matchedCount": 2
    },
    "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/conventional/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.333fremont.com/san-francisco/333-fremont/conventional/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.essexapartmenthomes.com/apartments/san-francisco/500-folsom/floor-plans-and-pricing": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (429)"
    },
    "https://www.rentcafe.com/apartments/ca/san-francisco/spera/default.aspx": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "lastSuccessfulAt": "2026-08-03T04:03:53.746Z",
      "matchedCount": 13
    },
    "https://www.zillow.com/apartments/san-francisco-ca/solaire/65g7KK/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/apartments/san-francisco-ca/jasper/5Yy5Rt/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/apartments/san-francisco-ca/388-beale/5XjQ4f/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/400-Beale-St-APT-1501-San-Francisco-CA-94105/80734962_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/318-Spear-St-UNIT-6B-San-Francisco-CA-94105/89236508_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/355-1st-St-UNIT-S2405-San-Francisco-CA-94105/64971613_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/355-1st-St-UNIT-S902-San-Francisco-CA-94105/2089159962_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T04:03:53.746Z",
      "error": "source blocked automated access (403)"
    }
  },
  "unitOverrides": {
    "340-1a-f7": {
      "active": true,
      "unit": "Unit 712 · 1 Bedroom A",
      "floor": 7,
      "beds": 1,
      "baths": 1,
      "sqft": 738,
      "rent": 5540,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "340-2s-f39": {
      "active": true,
      "unit": "Unit 3903 · 2 Bedroom S",
      "floor": 39,
      "beds": 2,
      "baths": 2,
      "sqft": 1118,
      "rent": 8634,
      "moveIn": "2026-08-14",
      "moveInLabel": "Aug 14",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-32e": {
      "active": true,
      "rent": 5481,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-26e": {
      "active": true,
      "rent": 5486,
      "moveIn": "2026-08-31",
      "moveInLabel": "Aug 31",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-32j": {
      "active": true,
      "rent": 5673,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-30j": {
      "active": true,
      "rent": 5713,
      "moveIn": "2026-08-05",
      "moveInLabel": "Aug 5",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-30i": {
      "active": true,
      "rent": 5496,
      "moveIn": "2026-08-24",
      "moveInLabel": "Aug 24",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-03h": {
      "active": true,
      "rent": 4886,
      "moveIn": "2026-08-19",
      "moveInLabel": "Aug 19",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-08h": {
      "active": true,
      "rent": 5012,
      "moveIn": "2026-09-01",
      "moveInLabel": "Sep 1",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-08b": {
      "active": true,
      "rent": 5212,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-32g": {
      "active": true,
      "rent": 5743,
      "moveIn": "2026-08-18",
      "moveInLabel": "Aug 18",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-19g": {
      "active": true,
      "rent": 5393,
      "moveIn": "2026-08-31",
      "moveInLabel": "Aug 31",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-23f": {
      "active": true,
      "rent": 6232,
      "moveIn": "2026-08-19",
      "moveInLabel": "Aug 19",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-ph33c": {
      "active": true,
      "rent": 16733,
      "moveIn": "2026-08-19",
      "moveInLabel": "Aug 19",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "spera-ph34c": {
      "active": true,
      "rent": 16833,
      "moveIn": "2026-09-03",
      "moveInLabel": "Sep 3",
      "checkedLabel": "Checked Aug 2, 2026"
    }
  },
  "discoveredUnits": []
};
