// Generated by scripts/refresh-listings.mjs after a successful source check.
export const refreshState = {
  "dataUpdatedAt": "2026-08-03T15:51:44.929Z",
  "previousDataUpdatedAt": "2026-08-03T05:06:05.105Z",
  "lastRefreshAttemptAt": "2026-08-03T15:51:44.929Z",
  "verifiedSourceCount": 6,
  "totalSourceCount": 14,
  "sourceStatuses": {
    "https://www.equityapartments.com/san-francisco/rincon-hill/340-fremont-apartments": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T15:51:44.929Z",
      "matchedCount": 2
    },
    "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/conventional/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T05:06:05.105Z",
      "matchedCount": 7,
      "error": "source blocked automated access (403)"
    },
    "https://www.333fremont.com/san-francisco/333-fremont/conventional/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T05:06:05.105Z",
      "matchedCount": 6,
      "error": "source blocked automated access (403)"
    },
    "https://www.essexapartmenthomes.com/apartments/san-francisco/500-folsom/floor-plans-and-pricing": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T05:06:05.105Z",
      "matchedCount": 15,
      "error": "source blocked automated access (429)"
    },
    "https://www.rentcafe.com/apartments/ca/san-francisco/spera/default.aspx": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T15:51:44.929Z",
      "matchedCount": 13
    },
    "https://solairesf.com/floorplans/": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T15:51:44.929Z",
      "matchedCount": 6
    },
    "https://www.rentjasper.com/community-map/": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T15:51:44.929Z",
      "matchedCount": 0
    },
    "https://www.udr.com/san-francisco-bay-area-apartments/san-francisco/388-beale/apartments-pricing/": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T15:51:44.929Z",
      "matchedCount": 12
    },
    "https://www.zillow.com/homedetails/400-Beale-St-APT-1501-San-Francisco-CA-94105/80734962_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/318-Spear-St-UNIT-6B-San-Francisco-CA-94105/89236508_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/355-1st-St-UNIT-S2405-San-Francisco-CA-94105/64971613_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/355-1st-St-UNIT-S902-San-Francisco-CA-94105/2089159962_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.zillow.com/homedetails/201-Folsom-St-APT-27D-San-Francisco-CA-94105/249698470_zpid/": {
      "status": "failed",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "error": "source blocked automated access (403)"
    },
    "https://www.compass.com/building/403-main-st-san-francisco-ca-94105/776839530855828237/": {
      "status": "verified",
      "lastAttemptAt": "2026-08-03T15:51:44.929Z",
      "lastSuccessfulAt": "2026-08-03T15:51:44.929Z",
      "matchedCount": 2
    }
  },
  "unitOverrides": {
    "340-1a-f7": {
      "active": true,
      "unit": "Unit 712 · 1 Bedroom A",
      "floor": 7,
      "beds": 1,
      "baths": 1,
      "sqft": 738,
      "rent": 5540,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.equityapartments.com/UnitFees/29921/1/712"
    },
    "340-2s-f39": {
      "active": true,
      "unit": "Unit 3903 · 2 Bedroom S",
      "floor": 39,
      "beds": 2,
      "baths": 2,
      "sqft": 1118,
      "rent": 8634,
      "moveIn": "2026-08-14",
      "moveInLabel": "Aug 14",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.equityapartments.com/UnitFees/29921/1/3903"
    },
    "spera-32e": {
      "active": true,
      "rent": 5481,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496942&FloorPlanID=5418875&header=1&MoveInDate=08/01/2026"
    },
    "spera-26e": {
      "active": true,
      "rent": 5486,
      "moveIn": "2026-08-31",
      "moveInLabel": "Aug 31",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496853&FloorPlanID=5418875&header=1&MoveInDate=09/02/2026"
    },
    "spera-32j": {
      "active": true,
      "rent": 5673,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496947&FloorPlanID=5418879&header=1&MoveInDate=08/01/2026"
    },
    "spera-30j": {
      "active": true,
      "rent": 5713,
      "moveIn": "2026-08-05",
      "moveInLabel": "Aug 5",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496921&FloorPlanID=5418879&header=1&MoveInDate=08/07/2026"
    },
    "spera-30i": {
      "active": true,
      "rent": 5496,
      "moveIn": "2026-08-24",
      "moveInLabel": "Aug 24",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496920&FloorPlanID=5417804&header=1&MoveInDate=08/26/2026"
    },
    "spera-03h": {
      "active": true,
      "rent": 4886,
      "moveIn": "2026-08-19",
      "moveInLabel": "Aug 19",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496956&FloorPlanID=5417805&header=1&MoveInDate=08/21/2026"
    },
    "spera-08h": {
      "active": true,
      "rent": 5012,
      "moveIn": "2026-09-01",
      "moveInLabel": "Sep 1",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42497017&FloorPlanID=5417805&header=1&MoveInDate=09/03/2026"
    },
    "spera-08b": {
      "active": true,
      "rent": 5212,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42497011&FloorPlanID=5418877&header=1&MoveInDate=08/05/2026"
    },
    "spera-32g": {
      "active": true,
      "rent": 5743,
      "moveIn": "2026-08-18",
      "moveInLabel": "Aug 18",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496944&FloorPlanID=5418878&header=1&MoveInDate=08/20/2026"
    },
    "spera-19g": {
      "active": true,
      "rent": 5393,
      "moveIn": "2026-08-31",
      "moveInLabel": "Aug 31",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496764&FloorPlanID=5418878&header=1&MoveInDate=09/02/2026"
    },
    "spera-23f": {
      "active": true,
      "rent": 6232,
      "moveIn": "2026-08-19",
      "moveInLabel": "Aug 19",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42496815&FloorPlanID=5418883&header=1&MoveInDate=08/21/2026"
    },
    "spera-ph33c": {
      "active": true,
      "rent": 16733,
      "moveIn": "2026-08-19",
      "moveInLabel": "Aug 19",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42497038&FloorPlanID=5418888&header=1&MoveInDate=08/21/2026"
    },
    "spera-ph34c": {
      "active": true,
      "rent": 16833,
      "moveIn": "2026-09-03",
      "moveInLabel": "Sep 3",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.rentcafe.com/onlineleasing/apartmentsforrent/oleapplication.aspx?Stepname=RentalOptions&myOlePropertyId=1857892&UnitID=42497042&FloorPlanID=5418888&header=1&MoveInDate=09/05/2026"
    },
    "solaire-2609": {
      "active": true,
      "unit": "Unit 2609 · Plan 09",
      "beds": 1,
      "baths": 1,
      "sqft": 610,
      "rent": 5418,
      "moveIn": "2026-07-22",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://solairesf.com/floorplans/unit-594f7022b67f043dd77d83d8acc3d06f/",
      "fees": 31.06
    },
    "solaire-2802": {
      "active": true,
      "unit": "Unit 2802 · Plan 02",
      "beds": 1,
      "baths": 1,
      "sqft": 513,
      "rent": 5408,
      "moveIn": "2026-08-24",
      "moveInLabel": "Aug 24",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://solairesf.com/floorplans/unit-64d57ffc3bd77e9c7db058c4df0193e0/",
      "fees": 31.06
    },
    "solaire-3103": {
      "active": true,
      "unit": "Unit 3103 · Plan 03",
      "beds": 1,
      "baths": 1,
      "sqft": 511,
      "rent": 5598,
      "moveIn": "2026-09-06",
      "moveInLabel": "Sep 6",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://solairesf.com/floorplans/unit-54c3bdbe168d5b46aeccb6a1b7bb512d/",
      "fees": 31.06
    },
    "solaire-1209": {
      "active": true,
      "unit": "Unit 1209 · Plan 09",
      "beds": 1,
      "baths": 1,
      "sqft": 610,
      "rent": 5043,
      "moveIn": "2026-09-07",
      "moveInLabel": "Sep 7",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://solairesf.com/floorplans/unit-f7ccdfefb4c70b7e3a57e9075b16073f/",
      "fees": 31.06
    },
    "solaire-2303": {
      "active": true,
      "unit": "Unit 2303 · Plan 03",
      "beds": 1,
      "baths": 1,
      "sqft": 511,
      "rent": 5358,
      "moveIn": "2026-09-12",
      "moveInLabel": "Sep 12",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://solairesf.com/floorplans/unit-6a3562dd197af54fb5ce400060d03400/",
      "fees": 31.06
    },
    "solaire-0509": {
      "active": true,
      "unit": "Unit 0509 · Plan 09",
      "beds": 1,
      "baths": 1,
      "sqft": 610,
      "rent": 4868,
      "moveIn": "2026-09-17",
      "moveInLabel": "Sep 17",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://solairesf.com/floorplans/unit-d17cbef2e38d6a3ba6791a623446b891/",
      "fees": 31.06
    },
    "388-1206": {
      "active": true,
      "unit": "Unit 1206 · Plan A1B",
      "beds": 1,
      "baths": 1,
      "sqft": 808,
      "rent": 6330,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=13&moveindate=08/04/2026&AvailableDateMilliseconds=1785801600000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 825
    },
    "388-1411": {
      "active": true,
      "unit": "Unit 1411 · Plan A1B",
      "beds": 1,
      "baths": 1,
      "sqft": 808,
      "rent": 6749,
      "moveIn": "2026-08-03",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=22&moveindate=08/04/2026&AvailableDateMilliseconds=1785801600000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 825
    },
    "388-1515": {
      "active": true,
      "unit": "Unit 1515 · Plan B2B",
      "beds": 2,
      "baths": 2,
      "sqft": 1211,
      "rent": 7592,
      "moveIn": "2026-08-04",
      "moveInLabel": "Aug 4",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=142&moveindate=08/05/2026&AvailableDateMilliseconds=1785888000000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 1225
    },
    "388-1516": {
      "active": true,
      "unit": "Unit 1516 · Plan A1C",
      "beds": 1,
      "baths": 1,
      "sqft": 825,
      "rent": 6072,
      "moveIn": "2026-08-06",
      "moveInLabel": "Aug 6",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=53&moveindate=08/06/2026&AvailableDateMilliseconds=1785974400000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 775
    },
    "388-1303": {
      "active": true,
      "unit": "Unit 1303 · Plan B2A",
      "beds": 2,
      "baths": 2,
      "sqft": 1164,
      "rent": 7744,
      "moveIn": "2026-08-20",
      "moveInLabel": "Aug 20",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=112&moveindate=08/20/2026&AvailableDateMilliseconds=1787184000000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 1125
    },
    "388-1415": {
      "active": true,
      "unit": "Unit 1415 · Plan B2B",
      "beds": 2,
      "baths": 2,
      "sqft": 1211,
      "rent": 7408,
      "moveIn": "2026-08-21",
      "moveInLabel": "Aug 21",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=140&moveindate=08/21/2026&AvailableDateMilliseconds=1787270400000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 1225
    },
    "388-1013": {
      "active": true,
      "unit": "Unit 1013 · Plan A1B",
      "beds": 1,
      "baths": 1,
      "sqft": 808,
      "rent": 6193,
      "moveIn": "2026-09-03",
      "moveInLabel": "Sep 3",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=7&moveindate=09/03/2026&AvailableDateMilliseconds=1788393600000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 825
    },
    "388-705": {
      "active": true,
      "unit": "Unit 705 · Plan A1G",
      "beds": 1,
      "baths": 1,
      "sqft": 951,
      "rent": 6200,
      "moveIn": "2026-09-17",
      "moveInLabel": "Sep 17",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=100&moveindate=09/17/2026&AvailableDateMilliseconds=1789603200000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 925
    },
    "388-701": {
      "active": true,
      "unit": "Unit 701 · Plan A1C",
      "beds": 1,
      "baths": 1,
      "sqft": 825,
      "rent": 6336,
      "moveIn": "2026-09-19",
      "moveInLabel": "Sep 19",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=39&moveindate=09/19/2026&AvailableDateMilliseconds=1789776000000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 775
    },
    "388-1808": {
      "active": true,
      "unit": "Unit 1808 · Plan A1F",
      "beds": 1,
      "baths": 1,
      "sqft": 861,
      "rent": 7194,
      "moveIn": "2026-09-26",
      "moveInLabel": "Sep 26",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=93&moveindate=09/26/2026&AvailableDateMilliseconds=1790380800000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 1100
    },
    "388-1709": {
      "active": true,
      "unit": "Unit 1709 · Plan B2G",
      "beds": 2,
      "baths": 2,
      "sqft": 1286,
      "rent": 7748,
      "moveIn": "2026-09-26",
      "moveInLabel": "Sep 26",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=203&moveindate=09/26/2026&AvailableDateMilliseconds=1790380800000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 1125
    },
    "388-703": {
      "active": true,
      "unit": "Unit 703 · Plan B2C",
      "beds": 2,
      "baths": 2,
      "sqft": 1214,
      "rent": 7422,
      "moveIn": "2026-10-03",
      "moveInLabel": "Oct 3",
      "checkedLabel": "Checked Aug 3, 2026",
      "listingUrl": "https://www.udr.com/leaseoll/floorplan/?pid=37412&realpagesiteid=2421377&unitid=152&moveindate=10/03/2026&AvailableDateMilliseconds=1790985600000&searchurl=https%3A%2F%2Fwww.udr.com%2FFormTemplates%2FRedirectCloseOverlay%3Fu%3D%252Fsan-francisco-bay-area-apartments%252Fsan-francisco%252F388-beale%252Fapartments-pricing%252F%253F&maxDaysToShow=49",
      "deposit": 1250
    },
    "modera-a03": {
      "active": true,
      "unit": "Plan A03",
      "beds": 1,
      "baths": 1,
      "sqft": 581,
      "rent": 4249,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/a03-992043/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "modera-a04": {
      "active": true,
      "unit": "Plan A04",
      "beds": 1,
      "baths": 1,
      "sqft": 673,
      "rent": 4568,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/a04-992046/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "modera-a10": {
      "active": true,
      "unit": "Plan A10",
      "beds": 1,
      "baths": 1,
      "sqft": 508,
      "rent": 4643,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/a10-992063/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "modera-b03": {
      "active": true,
      "unit": "Plan B03",
      "beds": 2,
      "baths": 2,
      "sqft": 914,
      "rent": 8003,
      "moveIn": "2026-08-08",
      "moveInLabel": "Aug 8",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/b03-992062/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "modera-b04": {
      "active": true,
      "unit": "Plan B04",
      "beds": 2,
      "baths": 1,
      "sqft": 892,
      "rent": 8110,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/b04-992058/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "modera-b06": {
      "active": true,
      "unit": "Plan B06",
      "beds": 2,
      "baths": 2,
      "sqft": 957,
      "rent": 8182,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/b06-992057/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "modera-b08": {
      "active": true,
      "unit": "Plan B08",
      "beds": 2,
      "baths": 2,
      "sqft": 988,
      "rent": 7700,
      "moveIn": "2026-08-08",
      "moveInLabel": "Aug 8",
      "checkedLabel": "Checked Aug 2, 2026",
      "listingUrl": "https://www.moderarinconhill.com/san-francisco-ca-apartments/modera-rincon-hill/floorplans/b08-992064/fp_name/occupancy_type/conventional/",
      "deposit": 500
    },
    "333-305": {
      "active": true,
      "rent": 5095,
      "moveIn": "2026-07-29",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "333-311": {
      "active": true,
      "rent": 5345,
      "moveIn": "2026-07-30",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "333-806": {
      "active": true,
      "rent": 5895,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "333-702": {
      "active": true,
      "rent": 6645,
      "moveIn": null,
      "moveInLabel": "Confirm date",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "333-208": {
      "active": true,
      "rent": 8049,
      "moveIn": "2026-08-17",
      "moveInLabel": "Aug 17",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "333-609": {
      "active": true,
      "rent": 8324,
      "moveIn": "2026-08-24",
      "moveInLabel": "Aug 24",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-1702": {
      "active": true,
      "unit": "Unit 1702 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 637,
      "rent": 5427,
      "moveIn": "2026-08-27",
      "moveInLabel": "Aug 27",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-0314": {
      "active": true,
      "unit": "Unit 0314 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 615,
      "rent": 5069,
      "moveIn": "2026-09-05",
      "moveInLabel": "Sep 5",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-2306": {
      "active": true,
      "unit": "Unit 2306 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 645,
      "rent": 5429,
      "moveIn": "2026-09-19",
      "moveInLabel": "Sep 19",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-2906": {
      "active": true,
      "unit": "Unit 2906 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 619,
      "rent": 5409,
      "moveIn": "2026-09-28",
      "moveInLabel": "Sep 28",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-1104": {
      "active": true,
      "unit": "Unit 1104 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 636,
      "rent": 5397,
      "moveIn": "2026-08-08",
      "moveInLabel": "Aug 8",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-2012": {
      "active": true,
      "unit": "Unit 2012 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 724,
      "rent": 5667,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-1212": {
      "active": true,
      "unit": "Unit 1212 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 699,
      "rent": 5549,
      "moveIn": "2026-08-31",
      "moveInLabel": "Aug 31",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-0322": {
      "active": true,
      "unit": "Unit 0322 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 855,
      "rent": 5647,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-0419": {
      "active": true,
      "unit": "Unit 0419 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 918,
      "rent": 5717,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-1203": {
      "active": true,
      "unit": "Unit 1203 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 813,
      "rent": 6197,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-2803": {
      "active": true,
      "unit": "Unit 2803 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 810,
      "rent": 6357,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-2211": {
      "active": true,
      "unit": "Unit 2211 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 769,
      "rent": 6277,
      "moveIn": "2026-09-03",
      "moveInLabel": "Sep 3",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-2003": {
      "active": true,
      "unit": "Unit 2003 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 879,
      "rent": 6387,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-1611": {
      "active": true,
      "unit": "Unit 1611 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 841,
      "rent": 6447,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "500-1803": {
      "active": true,
      "unit": "Unit 1803 · Plan Unknown",
      "beds": 1,
      "baths": 1,
      "sqft": 879,
      "rent": 6607,
      "moveIn": "2026-08-02",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 2, 2026"
    },
    "portside-316n": {
      "active": true,
      "unit": "Unit 316N",
      "beds": 1,
      "baths": 1,
      "sqft": 862,
      "rent": 5600,
      "moveIn": "2026-07-21",
      "moveInLabel": "Available now",
      "checkedLabel": "Checked Aug 3, 2026",
      "postedAt": "2026-07-21T07:00:00.000Z",
      "postedLabel": "Posted Jul 21, 2026",
      "listingUrl": "https://www.compass.com/homedetails/403-Main-St-Unit-316N-San-Francisco-CA-94105/1QGIEU_pid/"
    },
    "portside-717": {
      "active": true,
      "unit": "Unit 717",
      "beds": 1,
      "baths": 1,
      "sqft": 922,
      "rent": 5545,
      "moveIn": "2026-09-07",
      "moveInLabel": "Sep 7",
      "checkedLabel": "Checked Aug 3, 2026",
      "postedAt": "2026-08-01T07:00:00.000Z",
      "postedLabel": "Posted Aug 1, 2026",
      "listingUrl": "https://www.compass.com/homedetails/403-Main-St-Unit-717-San-Francisco-CA-94105/1QPSD2_pid/"
    }
  },
  "discoveredUnits": []
};
