// Generated by scripts/refresh-listings.mjs after a successful source check.
// Keeping this separate from the researched baseline makes failed refreshes harmless.
export const refreshState = {
  dataUpdatedAt: "2026-08-02T18:00:00-07:00",
  lastRefreshAttemptAt: null,
  verifiedSourceCount: 0,
  totalSourceCount: 12,
  sourceStatuses: {},
  unitOverrides: {},
  discoveredUnits: [],
};
